name: Publish
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Check
      run: |
        ls DDSU666/DDSU666/bin

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1.1.4
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: '${{ vars.PUBLISH_TAG_NAME }}'
    #     release_name: '${{ vars.PUBLISH_RELEASE_NAME }}/${{ vars.PUBLISH_TAG_NAME }}'
    #     body: ${{ vars.PUBLISH_CHANGES_BODY }}
    #     draft: false
    #     prerelease: false     

    # - name: Archive Database Release
    #   uses: thedoctor0/zip-release@0.7.6
    #   with:
    #     type: 'zip'
    #     filename: DDSU666
    #     directory: Fintrax.MMS.Database/bin/Output
    #     exclusions: '*.git* /*node_modules/* .editorconfig'     

    # - name: Upload Release Asset
    #   id: upload-release-asset1
    #   uses: actions/upload-release-asset@v1.0.2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: './Fintrax.MMS.Database/bin/Output/Database.zip'
    #     asset_name: 'Database.zip'
    #     asset_content_type: application/zip   
